import { Dimensions, PixelRatio } from "react-native";
import { NativeStackScreenProps } from "@react-navigation/native-stack";
import { useSelector } from "react-redux";
import { AppRootStore } from "../Redux/store/AppStore";

export const ScreenSize = Dimensions.get("screen");
const templateWidth = 375;
const templateHeight = 812;
export const isLargeWidth = Dimensions.get("window").width > 390;

export type ScreenProps = NativeStackScreenProps<any, any>;
export const fullDate = "Y-MM-DD HH:mm:ss.SSS Z";

export const maxImageSizeInBytes = 10 * 1024 * 1024; // 10MB

const widthRatio = ScreenSize.width / templateWidth;
const heightRatio = ScreenSize.height / templateHeight;
export const normalized = (value: number) =>
  PixelRatio.roundToNearestPixel(value * widthRatio);
export const hv = (value: number) =>
  PixelRatio.roundToNearestPixel(value * heightRatio);

export const AppHorizontalMargin = normalized(20);
export const bottomBarHeight = normalized(60);
export const isSmallDevice = ScreenSize.height < 700 ? true : false;

export const AppColors = {
  dark: {
    darkLevel1: "#535F79",
    darkLevel2: "#4B576E",
    darkLevel3: "#333E56",
    darkLevel4: "#232C3D",
    darkLevel5: "#21293B",
    darkLevel6: "#19202E",
    darkLevel7: "#10151B",
    darkLevel8: "#020101",
    darkLevel9: "#252525",
  },
  black: {
    black: "#000000",
    lightBlack: "#252525",
    black4: "#343A40",
    Level5: "#272727",
    Level6: "#202224",
    Level7: "#191D23",
    Level8: "#090b0e",
    Level9: "#101010",
  },
  white: {
    white: "#ffffff",
    whiteOp: "#E8E8E8",
    lightWhite: "#EEEEEE",
    creamy: "#ffe3e3",
    simple: "#f2f6fc",
    darkGrey: "#EDEDED",
  },
  grey: {
    greyLevel0: "#eeeeee",
    greyLevel1: "#E4E7EB",
    greyLevel2: "#C2C2C2",
    greyLevel3: "#D0D5DD",
    greyLevel4: "#8c8e91",
    greyLevel5: "#606060",
    greyLevel6: "#6B7280",
    greyLevel7: "#616161",
    greyLevel8: "#75777b",
    greyLevel9: "#909090",
    greyLevel10: "#F9F9F9",
    light: "#F7F6F4",
  },
  red: {
    dark: "#FF2B15",
    pink: "#fbe3e3",
  },
  themeColor: {
    dark: "#b00429",
    light: "#FEB851",
    medium: "#fab57d",
  },
  orange: {
    light: "#FDF1DB",
    dark: "#FE9311",
    sharp: "#DE8225",
  },
  green: {
    dark: "#00BE13",
    light: "#cbf5dd",
  },
  randomColor: {
    purpleDark: "rgba(43, 42, 105, 1)",
    purple: "#6E397D",
    black: "#000000",
    blue: "rgba(15, 69, 144, 1)",
    navy: "#135099",
  },
};

export const AppFonts = {
  PoppinsBlack: "Poppins-Black",
  PoppinsRegular: "Poppins-Regular",
  PoppinsSemiBold: "Poppins-SemiBold",
  PoppinsBold: "Poppins-Bold",
  PoppinsExtraBold: "Poppins-ExtraBold",
  PoppinsLight: "Poppins-Light",
  PoppinsExtraLight: "Poppins-ExtraLight",
  PoppinsItalic: "Poppins-Italic",
  PoppinsMedium: "Poppins-Medium",
  PoppinsThin: "Poppins-Thin",
  PoppinsBoldItalic: "Poppins-ExtraBoldItalic",
  PoppinsBlackItalic: "Poppins-BlackItalic",
  OpenSansRegular: "OpenSans-Regular",
  OpenSansSemiBold: "OpenSans-SemiBold",
  OpenSansBold: "OpenSans-Bold",
  OpenSansExtraBold: "OpenSans-ExtraBold",
  OpenSansLight: "OpenSans-Light",
  OpenSansExtraLight: "OpenSans-ExtraLight",
  OpenSansItalic: "OpenSans-Italic",
  OpenSansMedium: "OpenSans-Medium",
  OpenSansBoldItalic: "OpenSans-ExtraBoldItalic",
};

export const AppImages = {
  logo: require("../UI/assets/Images/logo.png"),
  Auth: {
    eye: require("../UI/assets/Images/Auth/Eye.png"),
    hideEye: require("../UI/assets/Images/Auth/hideEye.png"),
    message: require("../UI/assets/Images/Auth/Message.png"),
    google: require("../UI/assets/Images/Auth/Google.png"),
    dropdown: require("../UI/assets/Images/Auth/dropdown.png"),
    backArrow: require("../UI/assets/Images/Auth/BackArrow.png"),
    camera: require("../UI/assets/Images/Auth/camera.png"),
    apple: require("../UI/assets/Images/Auth/apple.png"),
    pin: require("../UI/assets/Images/Auth/pin.png"),
    flag: require("../UI/assets/Images/Auth/pakistan.png"),
  },
  Modal: {
    Camera: require("../UI/assets/Images/Home/CameraPicker.png"),
    Gallery: require("../UI/assets/Images/Home/GalleryPicker.png"),
  },
  Home: {
    tick: require("../UI/assets/Images/Profile/tick.png"),
    backArrow: require("../UI/assets/Images/Home/backArrow.png"),
    filter: require("../UI/assets/Images/Home/filter.png"),
    close: require("../UI/assets/Images/Home/CloseIcon.png"),
    cart: require("../UI/assets/Images/Home/cart.png"),
    star: require("../UI/assets/Images/Home/star.png"),
    PlusBlack: require("../UI/assets/Images/Home/plus.png"),
    Admin: require("../UI/assets/Images/Home/admin.png"),
    search: require("../UI/assets/Images/Home/Search.png"),
    silverBadge: require("../UI/assets/Images/Home/silver.png"),
    goldBadge: require("../UI/assets/Images/Home/gold.png"),
    badge: require("../UI/assets/Images/Home/badge.png"),
  },
  Products: {
    editIcon: require("../UI/assets/Images/products/editIcon.png"),
    delete: require("../UI/assets/Images/products/Delete.png"),
    emptyCart: require("../UI/assets/Images/products/emptyCart.png"),
    warning: require("../UI/assets/Images/products/warning.png"),
    category: require("../UI/assets/Images/products/category.png"),
    addProduct: require("../UI/assets/Images/products/add-product.png"),
    updateProduct: require("../UI/assets/Images/products/manage_product.png"),
  },
  bottomBar: {
    home: require("../UI/assets/Images/BottomBar/Home.png"),
    profile: require("../UI/assets/Images/BottomBar/profile.png"),
    notification: require("../UI/assets/Images/BottomBar/notification.png"),
    orders: require("../UI/assets/Images/BottomBar/orders.png"),
  },
  Profile: {
    ForwardArrow: require("../UI/assets/Images/Profile/forwardArrow.png"),
    ProfileIcon: require("../UI/assets/Images/Profile/profileIcon.png"),
    LocationIcon: require("../UI/assets/Images/Profile/location.png"),
    privacyIcon: require("../UI/assets/Images/Profile/privacyIcon.png"),
    SettingIcon: require("../UI/assets/Images/Profile/settingIcon.png"),
    LogoutIcon: require("../UI/assets/Images/Profile/logoutIcon.png"),
    deleteUser: require("../UI/assets/Images/Profile/deleteUser.png"),
    delivery: require("../UI/assets/Images/Profile/homeAddress.png"),
    cart: require("../UI/assets/Images/Profile/cart.png"),
    locationUnfilled: require("../UI/assets/Images/Profile/locationUnfilled.png"),
    street: require("../UI/assets/Images/Profile/street.png"),
    area: require("../UI/assets/Images/Profile/area.png"),
    city: require("../UI/assets/Images/Profile/city.png"),
    language: require("../UI/assets/Images/Profile/language.png"),
    usa: require("../UI/assets/Images/Profile/usa.png"),
    pk: require("../UI/assets/Images/Profile/pk.png"),
    password: require("../UI/assets/Images/Profile/password.png"),
  },
  User: {
    user: require("../UI/assets/Images/User/user.png"),
    phone: require("../UI/assets/Images/User/phone.png"),
    email: require("../UI/assets/Images/User/email.png"),
    orders: require("../UI/assets/Images/User/orders.png"),
    amount: require("../UI/assets/Images/User/amount.png"),
  },
  payments: {
    jazzcash: require("../UI/assets/Images/payment/jazzcash.png"),
    easypaisa: require("../UI/assets/Images/payment/easypaisa.png"),
    stamp: require("../UI/assets/Images/payment/stamp.png"),
  },
};

export const lottieAnimation = {
  tickAnimation: require("../UI/assets/animation/TickAnim.json"),
  closeAnimation: require("../UI/assets/animation/CloseAnim.json"),
  waringAnimation: require("../UI/assets/animation/warningAnim.json"),
};

export const imagePickerConstants = [
  {
    id: 0,
    image: AppImages.Modal.Gallery,
    text: "Upload from Gallery",
  },
  {
    id: 1,
    image: AppImages.Modal.Camera,
    text: "Take a photo from Camera",
  },
];

export const profileBarList = [
  {
    id: 1,
    text: "Edit Your Profile",
    rtlTxt: "اپنی پروفائل میں ترمیم کریں",
    leftIcon: AppImages.Profile.ProfileIcon,
  },
  {
    id: 2,
    text: "Delivery Address",
    rtlTxt: "ترسیل کا پتہ",
    leftIcon: AppImages.Profile.delivery,
  },
  {
    id: 7,
    text: "Change Password",
    rtlTxt: "پاس ورڈ تبدیل کریں",
    leftIcon: AppImages.Profile.password,
  },
  {
    id: 3,
    text: "My Cart",
    rtlTxt: "میری ٹوکری",
    leftIcon: AppImages.Profile.cart,
  },
  // {
  //   id: 6,
  //   text: "Select Language",
  //   rtlTxt: "زبان منتخب کریں",
  //   leftIcon: AppImages.Profile.language,
  // },
  {
    id: 4,
    text: "Delete Account",
    rtlTxt: "اکاؤنٹ حذف کریں",
    leftIcon: AppImages.Profile.deleteUser,
  },

  {
    id: 5,
    text: "Log out",
    rtlTxt: "لاگ آؤٹ",
    leftIcon: AppImages.Profile.LogoutIcon,
  },
];

export const adminProfileList = [
  {
    id: 1,
    text: "Edit Your Profile",
    rtlTxt: "اپنی پروفائل میں ترمیم کریں",
    leftIcon: AppImages.Profile.ProfileIcon,
  },

  // {
  //   id: 6,
  //   text: "Select Language",
  //   rtlTxt: "زبان منتخب کریں",
  //   leftIcon: AppImages.Profile.language,
  // },
  {
    id: 5,
    text: "Log out",
    rtlTxt: "لاگ آؤٹ",
    leftIcon: AppImages.Profile.LogoutIcon,
  },
];

export const guestProfileList = [
  {
    id: 5,
    text: "Log out",
    rtlTxt: "لاگ آؤٹ",
    leftIcon: AppImages.Profile.LogoutIcon,
  },
];

export const adminHomeBarItems = [
  {
    icon: AppImages.Products.category,
    title: "Manage Categories & Sub-Categories",
    rtlTitle: "کیٹگری اور سبکیٹگری کا انتظام کریں",
    id: 1,
  },
  {
    icon: AppImages.Products.addProduct,
    title: "Add New Products",
    rtlTitle: "نئے پروڈکٹس شامل کریں",
    id: 2,
  },
  {
    icon: AppImages.Products.updateProduct,
    title: "Update & Delete Existing Products",
    rtlTitle: "موجودہ پروڈکٹس کو اپ ڈیٹ اور حذف کریں",
    id: 3,
  },
  {
    icon: AppImages.Home.Admin,
    title: "Manage Multiple Admins",
    rtlTitle: "متعدد ایڈمنز کا انتظام کریں",
    id: 4,
  },
  {
    icon: AppImages.Home.Admin,
    title: "Add Category & Sub-Category",
    rtlTitle: "کیٹگری اور سبکیٹگری شامل کریں",
    id: 5,
  },
  {
    icon: AppImages.Home.badge,
    title: "Gold & Silver Customers",
    rtlTitle: "گولڈ اور سلور کسٹمرز",
    id: 6,
  },
];

export const Modal_Type = {
  deleteAccount: "DeleteAccount",
  logout: "Logout",
};

export const dummyProfile =
  "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/KPXaHR9D96ED07-63BE-4F4D-846B-7895376E50C3.jpg?alt=media&token=32340295-3a0d-41a7-abc5-9a744cdf9802";

export const prefixCodes: any = {
  AF: "93",
  AE: "971",
  AL: "355",
  AN: "599",
  AS: "1684",
  AD: "376",
  AO: "244",
  AI: "1264",
  AG: "1268",
  AR: "54",
  AM: "374",
  AW: "297",
  AU: "61",
  AT: "43",
  AZ: "994",
  BS: "1242",
  BH: "973",
  BF: "226",
  BI: "257",
  BD: "880",
  BB: "1246",
  BY: "375",
  BE: "32",
  BZ: "501",
  BJ: "229",
  BM: "1441",
  BT: "975",
  BA: "387",
  BW: "267",
  BR: "55",
  BG: "359",
  BO: "591",
  BL: "590",
  BN: "673",
  CC: "61",
  CD: "243",
  CI: "225",
  KH: "855",
  CM: "237",
  // CA: '1',
  CV: "238",
  KY: "345",
  CF: "236",
  CH: "41",
  CL: "56",
  CN: "86",
  CX: "61",
  CO: "57",
  KM: "269",
  CG: "242",
  CK: "682",
  CR: "506",
  CU: "53",
  CY: "537",
  CZ: "420",
  DE: "49",
  DK: "45",
  DJ: "253",
  DM: "1767",
  DO: "1849",
  DZ: "213",
  EC: "593",
  EG: "20",
  ER: "291",
  EE: "372",
  ES: "34",
  ET: "251",
  FM: "691",
  FK: "500",
  FO: "298",
  FJ: "679",
  FI: "358",
  FR: "33",
  GB: "44",
  GF: "594",
  GA: "241",
  GS: "500",
  GM: "220",
  GE: "995",
  GH: "233",
  GI: "350",
  GQ: "240",
  GR: "30",
  GG: "44",
  GL: "299",
  GD: "1473",
  GP: "590",
  GU: "1671",
  GT: "502",
  GN: "224",
  GW: "245",
  GY: "595",
  HT: "509",
  HR: "385",
  HN: "504",
  HU: "36",
  HK: "852",
  IR: "98",
  IM: "44",
  IL: "972",
  IO: "246",
  IS: "354",
  IN: "91",
  ID: "62",
  IQ: "964",
  IE: "353",
  IT: "39",
  JM: "1876",
  JP: "81",
  JO: "962",
  JE: "44",
  KP: "850",
  KR: "82",
  KZ: "77",
  KE: "254",
  KI: "686",
  KW: "965",
  KG: "996",
  KN: "1869",
  LC: "1758",
  LV: "371",
  LB: "961",
  LK: "94",
  LS: "266",
  LR: "231",
  LI: "423",
  LT: "370",
  LU: "352",
  LA: "856",
  LY: "218",
  MO: "853",
  MK: "389",
  MG: "261",
  MW: "265",
  MY: "60",
  MV: "960",
  ML: "223",
  MT: "356",
  MH: "692",
  MQ: "596",
  MR: "222",
  MU: "230",
  MX: "52",
  MC: "377",
  MN: "976",
  ME: "382",
  MP: "1670",
  MS: "1664",
  MA: "212",
  MM: "95",
  MF: "590",
  MD: "373",
  MZ: "258",
  NA: "264",
  NR: "674",
  NP: "977",
  NL: "31",
  NC: "687",
  NZ: "64",
  NI: "505",
  NE: "227",
  NG: "234",
  NU: "683",
  NF: "672",
  NO: "47",
  OM: "968",
  PK: "92",
  PM: "508",
  PW: "680",
  PF: "689",
  PA: "507",
  PG: "675",
  PY: "595",
  PE: "51",
  PH: "63",
  PL: "48",
  PN: "872",
  PT: "351",
  PR: "1939",
  PS: "970",
  QA: "974",
  RO: "40",
  RE: "262",
  RS: "381",
  RU: "7",
  RW: "250",
  SM: "378",
  SA: "966",
  SN: "221",
  SC: "248",
  SL: "232",
  SG: "65",
  SK: "421",
  SI: "386",
  SB: "677",
  SH: "290",
  SD: "249",
  SR: "597",
  SZ: "268",
  SE: "46",
  SV: "503",
  ST: "239",
  SO: "252",
  SJ: "47",
  SY: "963",
  TW: "886",
  TZ: "255",
  TL: "670",
  TD: "235",
  TJ: "992",
  TH: "66",
  TG: "228",
  TK: "690",
  TO: "676",
  TT: "1868",
  TN: "216",
  TR: "90",
  TM: "993",
  TC: "1649",
  TV: "688",
  UG: "256",
  UA: "380",
  US: "1",
  UY: "598",
  UZ: "998",
  VA: "379",
  VE: "58",
  VN: "84",
  VG: "1284",
  VI: "1340",
  VC: "1784",
  VU: "678",
  WS: "685",
  WF: "681",
  YE: "967",
  YT: "262",
  ZA: "27",
  ZM: "260",
  ZW: "263",
  AQ: "672",
};

export const countriesList: any = {
  AD: "Andorra",
  AE: "United Arab Emirates",
  AF: "Afghanistan",
  AG: "Antigua and Barbuda",
  AI: "Anguilla",
  AL: "Albania",
  AM: "Armenia",
  AO: "Angola",
  AQ: "Antarctica",
  AR: "Argentina",
  AS: "American Samoa",
  AT: "Austria",
  AU: "Australia",
  AW: "Aruba",
  AX: "Åland Islands",
  AZ: "Azerbaijan",
  BA: "Bosnia and Herzegovina",
  BB: "Barbados",
  BD: "Bangladesh",
  BE: "Belgium",
  BF: "Burkina Faso",
  BG: "Bulgaria",
  BH: "Bahrain",
  BI: "Burundi",
  BJ: "Benin",
  BL: "Saint Barthélemy",
  BM: "Bermuda",
  BN: "Brunei Darussalam",
  BO: "Bolivia (Plurinational State of)",
  BQ: "Bonaire, Sint Eustatius and Saba",
  BR: "Brazil",
  BS: "Bahamas",
  BT: "Bhutan",
  BV: "Bouvet Island",
  BW: "Botswana",
  BY: "Belarus",
  BZ: "Belize",
  CA: "Canada",
  CC: "Cocos (Keeling) Islands",
  CD: "Congo (Democratic Republic of the)",
  CF: "Central African Republic",
  CG: "Congo",
  CH: "Switzerland",
  CI: "Côte d'Ivoire",
  CK: "Cook Islands",
  CL: "Chile",
  CM: "Cameroon",
  CN: "China",
  CO: "Colombia",
  CR: "Costa Rica",
  CU: "Cuba",
  CV: "Cabo Verde",
  CW: "Curaçao",
  CX: "Christmas Island",
  CY: "Cyprus",
  CZ: "Czech Republic",
  DE: "Germany",
  DJ: "Djibouti",
  DK: "Denmark",
  DM: "Dominica",
  DO: "Dominican Republic",
  DZ: "Algeria",
  EC: "Ecuador",
  EE: "Estonia",
  EG: "Egypt",
  EH: "Western Sahara",
  ER: "Eritrea",
  ES: "Spain",
  ET: "Ethiopia",
  FI: "Finland",
  FJ: "Fiji",
  FK: "Falkland Islands (Malvinas)",
  FM: "Micronesia (Federated States of)",
  FO: "Faroe Islands",
  FR: "France",
  GA: "Gabon",
  GB: "United Kingdom of Great Britain and Northern Ireland",
  GD: "Grenada",
  GE: "Georgia",
  GF: "French Guiana",
  GG: "Guernsey",
  GH: "Ghana",
  GI: "Gibraltar",
  GL: "Greenland",
  GM: "Gambia",
  GN: "Guinea",
  GP: "Guadeloupe",
  GQ: "Equatorial Guinea",
  GR: "Greece",
  GS: "South Georgia and the South Sandwich Islands",
  GT: "Guatemala",
  GU: "Guam",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HK: "Hong Kong",
  HM: "Heard Island and McDonald Islands",
  HN: "Honduras",
  HR: "Croatia",
  HT: "Haiti",
  HU: "Hungary",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IM: "Isle of Man",
  IN: "India",
  IO: "British Indian Ocean Territory",
  IQ: "Iraq",
  IR: "Iran (Islamic Republic of)",
  IS: "Iceland",
  IT: "Italy",
  JE: "Jersey",
  JM: "Jamaica",
  JO: "Jordan",
  JP: "Japan",
  KE: "Kenya",
  KG: "Kyrgyzstan",
  KH: "Cambodia",
  KI: "Kiribati",
  KM: "Comoros",
  KN: "Saint Kitts and Nevis",
  KP: "Korea (Democratic People's Republic of)",
  KR: "Korea (Republic of)",
  KW: "Kuwait",
  KY: "Cayman Islands",
  KZ: "Kazakhstan",
  LA: "Lao People's Democratic Republic",
  LB: "Lebanon",
  LC: "Saint Lucia",
  LI: "Liechtenstein",
  LK: "Sri Lanka",
  LR: "Liberia",
  LS: "Lesotho",
  LT: "Lithuania",
  LU: "Luxembourg",
  LV: "Latvia",
  LY: "Libya",
  MA: "Morocco",
  MC: "Monaco",
  MD: "Moldova (Republic of)",
  ME: "Montenegro",
  MF: "Saint Martin (French part)",
  MG: "Madagascar",
  MH: "Marshall Islands",
  MK: "North Macedonia",
  ML: "Mali",
  MM: "Myanmar",
  MN: "Mongolia",
  MO: "Macao",
  MP: "Northern Mariana Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MS: "Montserrat",
  MT: "Malta",
  MU: "Mauritius",
  MV: "Maldives",
  MW: "Malawi",
  MX: "Mexico",
  MY: "Malaysia",
  MZ: "Mozambique",
  NA: "Namibia",
  NC: "New Caledonia",
  NE: "Niger",
  NF: "Norfolk Island",
  NG: "Nigeria",
  NI: "Nicaragua",
  NL: "Netherlands",
  NO: "Norway",
  NP: "Nepal",
  NR: "Nauru",
  NU: "Niue",
  NZ: "New Zealand",
  OM: "Oman",
  PA: "Panama",
  PE: "Peru",
  PF: "French Polynesia",
  PG: "Papua New Guinea",
  PH: "Philippines",
  PK: "Pakistan",
  PL: "Poland",
  PM: "Saint Pierre and Miquelon",
  PN: "Pitcairn",
  PR: "Puerto Rico",
  PS: "Palestine, State of",
  PT: "Portugal",
  PW: "Palau",
  PY: "Paraguay",
  QA: "Qatar",
  RE: "Réunion",
  RO: "Romania",
  RS: "Serbia",
  RU: "Russian Federation",
  RW: "Rwanda",
  SA: "Saudi Arabia",
  SB: "Solomon Islands",
  SC: "Seychelles",
  SD: "Sudan",
  SE: "Sweden",
  SG: "Singapore",
  SH: "Saint Helena, Ascension and Tristan da Cunha",
  SI: "Slovenia",
  SJ: "Svalbard and Jan Mayen",
  SK: "Slovakia",
  SL: "Sierra Leone",
  SM: "San Marino",
  SN: "Senegal",
  SO: "Somalia",
  SR: "Suriname",
  SS: "South Sudan",
  ST: "Sao Tome and Principe",
  SV: "El Salvador",
  SX: "Sint Maarten (Dutch part)",
  SY: "Syrian Arab Republic",
  SZ: "Eswatini",
  TC: "Turks and Caicos Islands",
  TD: "Chad",
  TF: "French Southern Territories",
  TG: "Togo",
  TH: "Thailand",
  TJ: "Tajikistan",
  TK: "Tokelau",
  TL: "Timor-Leste",
  TM: "Turkmenistan",
  TN: "Tunisia",
  TO: "Tonga",
  TR: "Turkey",
  TT: "Trinidad and Tobago",
  TV: "Tuvalu",
  TW: "Taiwan, Province of China",
  TZ: "Tanzania, United Republic of",
  UA: "Ukraine",
  UG: "Uganda",
  UM: "United States Minor Outlying Islands",
  US: "United States",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VA: "Holy See",
  VC: "Saint Vincent and the Grenadines",
  VE: "Venezuela (Bolivarian Republic of)",
  VG: "Virgin Islands (British)",
  VI: "Virgin Islands (U.S.)",
  VN: "Viet Nam",
  VU: "Vanuatu",
  WF: "Wallis and Futuna",
  WS: "Samoa",
  YE: "Yemen",
  YT: "Mayotte",
  ZA: "South Africa",
  ZM: "Zambia",
  ZW: "Zimbabwe",
};

export const countriesArray = [
  { key: 1, value: "AD", label: "Andorra", flag: "ad" },
  { key: 2, value: "AE", label: "United Arab Emirates", flag: "ae" },
  { key: 3, value: "AF", label: "Afghanistan", flag: "af" },
  { key: 4, value: "AG", label: "Antigua and Barbuda", flag: "ag" },
  { key: 5, value: "AI", label: "Anguilla", flag: "ai" },
  { key: 6, value: "AL", label: "Albania", flag: "al" },
  { key: 7, value: "AM", label: "Armenia", flag: "am" },
  { key: 8, value: "AO", label: "Angola", flag: "ao" },
  { key: 9, value: "AQ", label: "Antarctica", flag: "aq" },
  { key: 10, value: "AR", label: "Argentina", flag: "ar" },
  { key: 11, value: "AS", label: "American Samoa", flag: "as" },
  { key: 12, value: "AT", label: "Austria", flag: "at" },
  { key: 13, value: "AU", label: "Australia", flag: "au" },
  { key: 14, value: "AW", label: "Aruba", flag: "aw" },
  { key: 15, value: "AX", label: "Åland Islands", flag: "ax" },
  { key: 16, value: "AZ", label: "Azerbaijan", flag: "az" },
  { key: 17, value: "BA", label: "Bosnia and Herzegovina", flag: "ba" },
  { key: 18, value: "BB", label: "Barbados", flag: "bb" },
  { key: 19, value: "BD", label: "Bangladesh", flag: "bd" },
  { key: 20, value: "BE", label: "Belgium", flag: "be" },
  { key: 21, value: "BF", label: "Burkina Faso", flag: "bf" },
  { key: 22, value: "BG", label: "Bulgaria", flag: "bg" },
  { key: 23, value: "BH", label: "Bahrain", flag: "bh" },
  { key: 24, value: "BI", label: "Burundi", flag: "bi" },
  { key: 25, value: "BJ", label: "Benin", flag: "bj" },
  { key: 26, value: "BL", label: "Saint Barthélemy", flag: "bl" },
  { key: 27, value: "BM", label: "Bermuda", flag: "bm" },
  { key: 28, value: "BN", label: "Brunei Darussalam", flag: "bn" },
  {
    key: 29,
    value: "BO",
    label: "Bolivia (Plurinational State of)",
    flag: "bo",
  },
  {
    key: 30,
    value: "BQ",
    label: "Bonaire, Sint Eustatius and Saba",
    flag: "bq",
  },
  { key: 31, value: "BR", label: "Brazil", flag: "br" },
  { key: 32, value: "BS", label: "Bahamas", flag: "bs" },
  { key: 33, value: "BT", label: "Bhutan", flag: "bt" },
  { key: 34, value: "BV", label: "Bouvet Island", flag: "bv" },
  { key: 35, value: "BW", label: "Botswana", flag: "bw" },
  { key: 36, value: "BY", label: "Belarus", flag: "by" },
  { key: 37, value: "BZ", label: "Belize", flag: "bz" },
  { key: 38, value: "CA", label: "Canada", flag: "ca" },
  { key: 39, value: "CC", label: "Cocos (Keeling) Islands", flag: "cc" },
  {
    key: 40,
    value: "CD",
    label: "Congo (Democratic Republic of the)",
    flag: "cd",
  },
  { key: 41, value: "CF", label: "Central African Republic", flag: "cf" },
  { key: 42, value: "CG", label: "Congo", flag: "cg" },
  { key: 43, value: "CH", label: "Switzerland", flag: "ch" },
  { key: 44, value: "CI", label: "Côte d'Ivoire", flag: "ci" },
  { key: 45, value: "CK", label: "Cook Islands", flag: "ck" },
  { key: 46, value: "CL", label: "Chile", flag: "cl" },
  { key: 47, value: "CM", label: "Cameroon", flag: "cm" },
  { key: 48, value: "CN", label: "China", flag: "cn" },
  { key: 49, value: "CO", label: "Colombia", flag: "co" },
  { key: 50, value: "CR", label: "Costa Rica", flag: "cr" },
  { key: 51, value: "CU", label: "Cuba", flag: "cu" },
  { key: 52, value: "CV", label: "Cabo Verde", flag: "cv" },
  { key: 53, value: "CW", label: "Curaçao", flag: "cw" },
  { key: 54, value: "CX", label: "Christmas Island", flag: "cx" },
  { key: 55, value: "CY", label: "Cyprus", flag: "cy" },
  { key: 56, value: "CZ", label: "Czech Republic", flag: "cz" },
  { key: 57, value: "DE", label: "Germany", flag: "de" },
  { key: 58, value: "DJ", label: "Djibouti", flag: "dj" },
  { key: 59, value: "DK", label: "Denmark", flag: "dk" },
  { key: 60, value: "DM", label: "Dominica", flag: "dm" },
  { key: 61, value: "DO", label: "Dominican Republic", flag: "do" },
  { key: 62, value: "DZ", label: "Algeria", flag: "dz" },
  { key: 63, value: "EC", label: "Ecuador", flag: "ec" },
  { key: 64, value: "EE", label: "Estonia", flag: "ee" },
  { key: 65, value: "EG", label: "Egypt", flag: "eg" },
  { key: 66, value: "EH", label: "Western Sahara", flag: "eh" },
  { key: 67, value: "ER", label: "Eritrea", flag: "er" },
  { key: 68, value: "ES", label: "Spain", flag: "es" },
  { key: 69, value: "ET", label: "Ethiopia", flag: "et" },
  { key: 70, value: "FI", label: "Finland", flag: "fi" },
  { key: 71, value: "FJ", label: "Fiji", flag: "fj" },
  { key: 72, value: "FK", label: "Falkland Islands (Malvinas)", flag: "fk" },
  {
    key: 73,
    value: "FM",
    label: "Micronesia (Federated States of)",
    flag: "fm",
  },
  { key: 74, value: "FO", label: "Faroe Islands", flag: "fo" },
  { key: 75, value: "FR", label: "France", flag: "fr" },
  { key: 76, value: "GA", label: "Gabon", flag: "ga" },
  {
    key: 77,
    value: "GB",
    label: "United Kingdom of Great Britain and Northern Ireland",
    flag: "gb",
  },
  { key: 78, value: "GD", label: "Grenada", flag: "gd" },
  { key: 79, value: "GE", label: "Georgia", flag: "ge" },
  { key: 80, value: "GF", label: "French Guiana", flag: "gf" },
  { key: 81, value: "GG", label: "Guernsey", flag: "gg" },
  { key: 82, value: "GH", label: "Ghana", flag: "gh" },
  { key: 83, value: "GI", label: "Gibraltar", flag: "gi" },
  { key: 84, value: "GL", label: "Greenland", flag: "gl" },
  { key: 85, value: "GM", label: "Gambia", flag: "gm" },
  { key: 86, value: "GN", label: "Guinea", flag: "gn" },
  { key: 87, value: "GP", label: "Guadeloupe", flag: "gp" },
  { key: 88, value: "GQ", label: "Equatorial Guinea", flag: "gq" },
  { key: 89, value: "GR", label: "Greece", flag: "gr" },
  {
    key: 90,
    value: "GS",
    label: "South Georgia and the South Sandwich Islands",
    flag: "gs",
  },
  { key: 91, value: "GT", label: "Guatemala", flag: "gt" },
  { key: 92, value: "GU", label: "Guam", flag: "gu" },
  { key: 93, value: "GW", label: "Guinea-Bissau", flag: "gw" },
  { key: 94, value: "GY", label: "Guyana", flag: "gy" },
  { key: 95, value: "HK", label: "Hong Kong", flag: "hk" },
  {
    key: 96,
    value: "HM",
    label: "Heard Island and McDonald Islands",
    flag: "hm",
  },
  { key: 97, value: "HN", label: "Honduras", flag: "hn" },
  { key: 98, value: "HR", label: "Croatia", flag: "hr" },
  { key: 99, value: "HT", label: "Haiti", flag: "ht" },
  { key: 100, value: "HU", label: "Hungary", flag: "hu" },
  { key: 101, value: "ID", label: "Indonesia", flag: "id" },
  { key: 102, value: "IE", label: "Ireland", flag: "ie" },
  { key: 103, value: "IL", label: "Israel", flag: "il" },
  { key: 104, value: "IM", label: "Isle of Man", flag: "im" },
  { key: 105, value: "IN", label: "India", flag: "in" },
  {
    key: 106,
    value: "IO",
    label: "British Indian Ocean Territory",
    flag: "io",
  },
  { key: 107, value: "IQ", label: "Iraq", flag: "iq" },
  { key: 108, value: "IR", label: "Iran (Islamic Republic of)", flag: "ir" },
  { key: 109, value: "IS", label: "Iceland", flag: "is" },
  { key: 110, value: "IT", label: "Italy", flag: "it" },
  { key: 111, value: "JE", label: "Jersey", flag: "je" },
  { key: 112, value: "JM", label: "Jamaica", flag: "jm" },
  { key: 113, value: "JO", label: "Jordan", flag: "jo" },
  { key: 114, value: "JP", label: "Japan", flag: "jp" },
  { key: 115, value: "KE", label: "Kenya", flag: "ke" },
  { key: 116, value: "KG", label: "Kyrgyzstan", flag: "kg" },
  { key: 117, value: "KH", label: "Cambodia", flag: "kh" },
  { key: 118, value: "KI", label: "Kiribati", flag: "ki" },
  { key: 119, value: "KM", label: "Comoros", flag: "km" },
  { key: 120, value: "KN", label: "Saint Kitts and Nevis", flag: "kn" },
  {
    key: 121,
    value: "KP",
    label: "Korea (Democratic People's Republic of)",
    flag: "kp",
  },
  { key: 122, value: "KR", label: "Korea (Republic of)", flag: "kr" },
  { key: 123, value: "KW", label: "Kuwait", flag: "kw" },
  { key: 124, value: "KY", label: "Cayman Islands", flag: "ky" },
  { key: 125, value: "KZ", label: "Kazakhstan", flag: "kz" },
  {
    key: 126,
    value: "LA",
    label: "Lao People's Democratic Republic",
    flag: "la",
  },
  { key: 127, value: "LB", label: "Lebanon", flag: "lb" },
  { key: 128, value: "LC", label: "Saint Lucia", flag: "lc" },
  { key: 129, value: "LI", label: "Liechtenstein", flag: "li" },
  { key: 130, value: "LK", label: "Sri Lanka", flag: "lk" },
  { key: 131, value: "LR", label: "Liberia", flag: "lr" },
  { key: 132, value: "LS", label: "Lesotho", flag: "ls" },
  { key: 133, value: "LT", label: "Lithuania", flag: "lt" },
  { key: 134, value: "LU", label: "Luxembourg", flag: "lu" },
  { key: 135, value: "LV", label: "Latvia", flag: "lv" },
  { key: 136, value: "LY", label: "Libya", flag: "ly" },
  { key: 137, value: "MA", label: "Morocco", flag: "ma" },
  { key: 138, value: "MC", label: "Monaco", flag: "mc" },
  { key: 139, value: "MD", label: "Moldova (Republic of)", flag: "md" },
  { key: 140, value: "ME", label: "Montenegro", flag: "me" },
  { key: 141, value: "MF", label: "Saint Martin (French part)", flag: "mf" },
  { key: 142, value: "MG", label: "Madagascar", flag: "mg" },
  { key: 143, value: "MH", label: "Marshall Islands", flag: "mh" },
  { key: 144, value: "MK", label: "North Macedonia", flag: "mk" },
  { key: 145, value: "ML", label: "Mali", flag: "ml" },
  { key: 146, value: "MM", label: "Myanmar", flag: "mm" },
  { key: 147, value: "MN", label: "Mongolia", flag: "mn" },
  { key: 148, value: "MO", label: "Macao", flag: "mo" },
  { key: 149, value: "MP", label: "Northern Mariana Islands", flag: "mp" },
  { key: 150, value: "MQ", label: "Martinique", flag: "mq" },
  { key: 151, value: "MR", label: "Mauritania", flag: "mr" },
  { key: 152, value: "MS", label: "Montserrat", flag: "ms" },
  { key: 153, value: "MT", label: "Malta", flag: "mt" },
  { key: 154, value: "MU", label: "Mauritius", flag: "mu" },
  { key: 155, value: "MV", label: "Maldives", flag: "mv" },
  { key: 156, value: "MW", label: "Malawi", flag: "mw" },
  { key: 157, value: "MX", label: "Mexico", flag: "mx" },
  { key: 158, value: "MY", label: "Malaysia", flag: "my" },
  { key: 159, value: "MZ", label: "Mozambique", flag: "mz" },
  { key: 160, value: "NA", label: "Namibia", flag: "na" },
  { key: 161, value: "NC", label: "New Caledonia", flag: "nc" },
  { key: 162, value: "NE", label: "Niger", flag: "ne" },
  { key: 163, value: "NF", label: "Norfolk Island", flag: "nf" },
  { key: 164, value: "NG", label: "Nigeria", flag: "ng" },
  { key: 165, value: "NI", label: "Nicaragua", flag: "ni" },
  { key: 166, value: "NL", label: "Netherlands", flag: "nl" },
  { key: 167, value: "NO", label: "Norway", flag: "no" },
  { key: 168, value: "NP", label: "Nepal", flag: "np" },
  { key: 169, value: "NR", label: "Nauru", flag: "nr" },
  { key: 170, value: "NU", label: "Niue", flag: "nu" },
  { key: 171, value: "NZ", label: "New Zealand", flag: "nz" },
  { key: 172, value: "OM", label: "Oman", flag: "om" },
  { key: 173, value: "PA", label: "Panama", flag: "pa" },
  { key: 174, value: "PE", label: "Peru", flag: "pe" },
  { key: 175, value: "PF", label: "French Polynesia", flag: "pf" },
  { key: 176, value: "PG", label: "Papua New Guinea", flag: "pg" },
  { key: 177, value: "PH", label: "Philippines", flag: "ph" },
  { key: 178, value: "PK", label: "Pakistan", flag: "pk" },
  { key: 179, value: "PL", label: "Poland", flag: "pl" },
  { key: 180, value: "PM", label: "Saint Pierre and Miquelon", flag: "pm" },
  { key: 181, value: "PN", label: "Pitcairn", flag: "pn" },
  { key: 182, value: "PR", label: "Puerto Rico", flag: "pr" },
  { key: 183, value: "PS", label: "Palestine, State of", flag: "ps" },
  { key: 184, value: "PT", label: "Portugal", flag: "pt" },
  { key: 185, value: "PW", label: "Palau", flag: "pw" },
  { key: 186, value: "PY", label: "Paraguay", flag: "py" },
  { key: 187, value: "QA", label: "Qatar", flag: "qa" },
  { key: 188, value: "RE", label: "Réunion", flag: "re" },
  { key: 189, value: "RO", label: "Romania", flag: "ro" },
  { key: 190, value: "RS", label: "Serbia", flag: "rs" },
  { key: 191, value: "RU", label: "Russian Federation", flag: "ru" },
  { key: 192, value: "RW", label: "Rwanda", flag: "rw" },
  { key: 193, value: "SA", label: "Saudi Arabia", flag: "sa" },
  { key: 194, value: "SB", label: "Solomon Islands", flag: "sb" },
  { key: 195, value: "SC", label: "Seychelles", flag: "sc" },
  { key: 196, value: "SD", label: "Sudan", flag: "sd" },
  { key: 197, value: "SE", label: "Sweden", flag: "se" },
  { key: 198, value: "SG", label: "Singapore", flag: "sg" },
  {
    key: 199,
    value: "SH",
    label: "Saint Helena, Ascension and Tristan da Cunha",
    flag: "sh",
  },
  { key: 200, value: "SI", label: "Slovenia", flag: "si" },
  { key: 201, value: "SJ", label: "Svalbard and Jan Mayen", flag: "sj" },
  { key: 202, value: "SK", label: "Slovakia", flag: "sk" },
  { key: 203, value: "SL", label: "Sierra Leone", flag: "sl" },
  { key: 204, value: "SM", label: "San Marino", flag: "sm" },
  { key: 205, value: "SN", label: "Senegal", flag: "sn" },
  { key: 206, value: "SO", label: "Somalia", flag: "so" },
  { key: 207, value: "SR", label: "Suriname", flag: "sr" },
  { key: 208, value: "SS", label: "South Sudan", flag: "ss" },
  { key: 209, value: "ST", label: "Sao Tome and Principe", flag: "st" },
  { key: 210, value: "SV", label: "El Salvador", flag: "sv" },
  { key: 211, value: "SX", label: "Sint Maarten (Dutch part)", flag: "sx" },
  { key: 212, value: "SY", label: "Syrian Arab Republic", flag: "sy" },
  { key: 213, value: "SZ", label: "Eswatini", flag: "sz" },
  { key: 214, value: "TC", label: "Turks and Caicos Islands", flag: "tc" },
  { key: 215, value: "TD", label: "Chad", flag: "td" },
  { key: 216, value: "TF", label: "French Southern Territories", flag: "tf" },
  { key: 217, value: "TG", label: "Togo", flag: "tg" },
  { key: 218, value: "TH", label: "Thailand", flag: "th" },
  { key: 219, value: "TJ", label: "Tajikistan", flag: "tj" },
  { key: 220, value: "TK", label: "Tokelau", flag: "tk" },
  { key: 221, value: "TL", label: "Timor-Leste", flag: "tl" },
  { key: 222, value: "TM", label: "Turkmenistan", flag: "tm" },
  { key: 223, value: "TN", label: "Tunisia", flag: "tn" },
  { key: 224, value: "TO", label: "Tonga", flag: "to" },
  { key: 225, value: "TR", label: "Turkey", flag: "tr" },
  { key: 226, value: "TT", label: "Trinidad and Tobago", flag: "tt" },
  { key: 227, value: "TV", label: "Tuvalu", flag: "tv" },
  { key: 228, value: "TW", label: "Taiwan", flag: "tw" },
  { key: 229, value: "TZ", label: "Tanzania, United Republic of", flag: "tz" },
  { key: 230, value: "UA", label: "Ukraine", flag: "ua" },
  { key: 231, value: "UG", label: "Uganda", flag: "ug" },
  {
    key: 232,
    value: "UM",
    label: "United States Minor Outlying Islands",
    flag: "um",
  },
  { key: 233, value: "US", label: "United States of America", flag: "us" },
  { key: 234, value: "UY", label: "Uruguay", flag: "uy" },
  { key: 235, value: "UZ", label: "Uzbekistan", flag: "uz" },
  { key: 236, value: "VA", label: "Holy See", flag: "va" },
  {
    key: 237,
    value: "VC",
    label: "Saint Vincent and the Grenadines",
    flag: "vc",
  },
  {
    key: 238,
    value: "VE",
    label: "Venezuela (Bolivarian Republic of)",
    flag: "ve",
  },
  { key: 239, value: "VG", label: "Virgin Islands (British)", flag: "vg" },
  { key: 240, value: "VI", label: "Virgin Islands (U.S.)", flag: "vi" },
  { key: 241, value: "VN", label: "Viet Nam", flag: "vn" },
  { key: 242, value: "VU", label: "Vanuatu", flag: "vu" },
  { key: 243, value: "WF", label: "Wallis and Futuna", flag: "wf" },
  { key: 244, value: "WS", label: "Samoa", flag: "ws" },
  { key: 245, value: "YE", label: "Yemen", flag: "ye" },
  { key: 246, value: "YT", label: "Mayotte", flag: "yt" },
  { key: 247, value: "ZA", label: "South Africa", flag: "za" },
  { key: 248, value: "ZM", label: "Zambia", flag: "zm" },
  { key: 249, value: "ZW", label: "Zimbabwe", flag: "zw" },
];

export const Categories = [
  {
    id: 101,
    category: "Engine Components",
    subcategories: [
      { id: 1011, name: "Pistons & Rings" },
      { id: 1012, name: "Cylinder Heads" },
      { id: 1013, name: "Crankshafts" },
      { id: 1014, name: "Timing Belts" },
      { id: 1015, name: "Gaskets & Seals" },
      { id: 1016, name: "Camshafts" },
      { id: 1017, name: "Oil Pumps" },
      { id: 1018, name: "Valves & Lifters" },
      { id: 1019, name: "Connecting Rods" },
      { id: 1020, name: "Turbochargers" },
    ],
  },
  {
    id: 102,
    category: "Braking System",
    subcategories: [
      { id: 1021, name: "Brake Pads" },
      { id: 1022, name: "Brake Rotors" },
      { id: 1023, name: "Brake Calipers" },
      { id: 1024, name: "Brake Drums" },
      { id: 1025, name: "Master Cylinders" },
      { id: 1026, name: "Brake Lines & Hoses" },
      { id: 1027, name: "ABS Sensors" },
      { id: 1028, name: "Brake Shoes" },
      { id: 1029, name: "Handbrake Components" },
      { id: 1030, name: "Brake Fluid Reservoirs" },
    ],
  },
  {
    id: 103,
    category: "Suspension & Steering",
    subcategories: [
      { id: 1031, name: "Shock Absorbers" },
      { id: 1032, name: "Struts" },
      { id: 1033, name: "Control Arms" },
      { id: 1034, name: "Tie Rod Ends" },
      { id: 1035, name: "Ball Joints" },
      { id: 1036, name: "Sway Bars" },
      { id: 1037, name: "Steering Racks" },
      { id: 1038, name: "Power Steering Pumps" },
      { id: 1039, name: "Bushings" },
      { id: 1040, name: "Wheel Bearings" },
    ],
  },
  {
    id: 104,
    category: "Transmission System",
    subcategories: [
      { id: 1041, name: "Clutches" },
      { id: 1042, name: "Gearboxes" },
      { id: 1043, name: "Drive Shafts" },
      { id: 1044, name: "Differentials" },
      { id: 1045, name: "CV Joints" },
      { id: 1046, name: "Flywheels" },
      { id: 1047, name: "Shift Cables" },
      { id: 1048, name: "Torque Converters" },
      { id: 1049, name: "Transmission Fluids" },
      { id: 1050, name: "Axles" },
    ],
  },
  {
    id: 105,
    category: "Electrical & Lighting",
    subcategories: [
      { id: 1051, name: "Headlights" },
      { id: 1052, name: "Taillights" },
      { id: 1053, name: "Alternators" },
      { id: 1054, name: "Batteries" },
      { id: 1055, name: "Spark Plugs" },
      { id: 1056, name: "Ignition Coils" },
      { id: 1057, name: "Fuses & Relays" },
      { id: 1058, name: "Wiring Harnesses" },
      { id: 1059, name: "Turn Signals" },
      { id: 1060, name: "Horn Assemblies" },
    ],
  },
  {
    id: 106,
    category: "Exhaust System",
    subcategories: [
      { id: 1061, name: "Mufflers" },
      { id: 1062, name: "Catalytic Converters" },
      { id: 1063, name: "Exhaust Manifolds" },
      { id: 1064, name: "Oxygen Sensors" },
      { id: 1065, name: "Resonators" },
      { id: 1066, name: "Exhaust Pipes" },
      { id: 1067, name: "Heat Shields" },
      { id: 1068, name: "EGR Valves" },
      { id: 1069, name: "Tailpipes" },
      { id: 1070, name: "Exhaust Gaskets" },
    ],
  },
  {
    id: 107,
    category: "Cooling System",
    subcategories: [
      { id: 1071, name: "Radiators" },
      { id: 1072, name: "Water Pumps" },
      { id: 1073, name: "Thermostats" },
      { id: 1074, name: "Coolant Hoses" },
      { id: 1075, name: "Cooling Fans" },
      { id: 1076, name: "Fan Clutches" },
      { id: 1077, name: "Heater Cores" },
      { id: 1078, name: "Expansion Tanks" },
      { id: 1079, name: "Coolant Sensors" },
      { id: 1080, name: "Intercoolers" },
    ],
  },
  {
    id: 108,
    category: "Fuel System",
    subcategories: [
      { id: 1081, name: "Fuel Pumps" },
      { id: 1082, name: "Fuel Injectors" },
      { id: 1083, name: "Carburetors" },
      { id: 1084, name: "Fuel Filters" },
      { id: 1085, name: "Fuel Lines" },
      { id: 1086, name: "Throttle Bodies" },
      { id: 1087, name: "Fuel Pressure Regulators" },
      { id: 1088, name: "Gas Caps" },
      { id: 1089, name: "Fuel Rails" },
      { id: 1090, name: "Air Filters" },
    ],
  },
  {
    id: 109,
    category: "Body & Exterior",
    subcategories: [
      { id: 1091, name: "Bumpers" },
      { id: 1092, name: "Grilles" },
      { id: 1093, name: "Fenders" },
      { id: 1094, name: "Doors" },
      { id: 1095, name: "Mirrors" },
      { id: 1096, name: "Windows" },
      { id: 1097, name: "Spoilers" },
      { id: 1098, name: "Side Skirts" },
      { id: 1099, name: "Hood & Trunk Latches" },
      { id: 1100, name: "Roof Racks" },
    ],
  },
];

export const dummyList = [
  {
    name: "Bike Tyres",
    price: "8000",
    images: [
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
    ],
    productId: "45XG3441",
    category: "Body & Exterior",
    subCategory: "Doors",
    description:
      "Conquer rugged trails and steep hills with this durable and lightweight mountain bike. Built with advanced suspension and high-traction tires, it's perfect for off-road adventures and challenging terrains.",
  },
  {
    name: "Bike Tyres",
    price: 8000,
    images: [
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
    ],
    productId: "45XG3440",
    category: "Body & Exterior",
    subCategory: "Doors",
    description:
      "Conquer rugged trails and steep hills with this durable and lightweight mountain bike. Built with advanced suspension and high-traction tires, it's perfect for off-road adventures and challenging terrains.",
  },
  {
    name: "Bike Tyres",
    price: 8000,
    images: [
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
    ],
    productId: "45XG3442",
    category: "Body & Exterior",
    subCategory: "Doors",
    description:
      "Conquer rugged trails and steep hills with this durable and lightweight mountain bike. Built with advanced suspension and high-traction tires, it's perfect for off-road adventures and challenging terrains.",
  },
  {
    name: "Bike Tyres",
    price: 8000,
    images: [
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
    ],
    productId: "45XG3443",
    category: "Body & Exterior",
    subCategory: "Doors",
    description:
      "Conquer rugged trails and steep hills with this durable and lightweight mountain bike. Built with advanced suspension and high-traction tires, it's perfect for off-road adventures and challenging terrains.",
  },
  {
    name: "Bike Tyres",
    price: 8000,
    images: [
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
    ],
    productId: "45XG3444",
    category: "Body & Exterior",
    subCategory: "Doors",
    description:
      "Conquer rugged trails and steep hills with this durable and lightweight mountain bike. Built with advanced suspension and high-traction tires, it's perfect for off-road adventures and challenging terrains.",
  },
  {
    name: "Bike Tyres",
    price: 8000,
    images: [
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
    ],
    productId: "45XG3445",
    category: "Body & Exterior",
    subCategory: "Doors",
    description:
      "Conquer rugged trails and steep hills with this durable and lightweight mountain bike. Built with advanced suspension and high-traction tires, it's perfect for off-road adventures and challenging terrains.",
  },
  {
    name: "Bike Tyres",
    price: 8000,
    images: [
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
    ],
    productId: "45XG3446",
    category: "Body & Exterior",
    subCategory: "Doors",
    description:
      "Conquer rugged trails and steep hills with this durable and lightweight mountain bike. Built with advanced suspension and high-traction tires, it's perfect for off-road adventures and challenging terrains.",
  },
  {
    name: "Bike Tyres",
    price: 8000,
    category: "Body & Exterior",
    subCategory: "Doors",
    images: [
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
    ],
    productId: "45XG3447",
    description:
      "Conquer rugged trails and steep hills with this durable and lightweight mountain bike. Built with advanced suspension and high-traction tires, it's perfect for off-road adventures and challenging terrains.",
  },
  {
    name: "Bike Tyres",
    price: 8000,
    images: [
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
      "https://firebasestorage.googleapis.com:443/v0/b/zippy-6ae4c.appspot.com/o/aPdZjzFB883E3B-14F9-4179-8E09-04AF917E667E.jpg?alt=media&token=3db7e6ad-4041-49e2-ac6c-e6fc418be435",
    ],
    productId: "45XG3448",
    category: "Body & Exterior",
    subCategory: "Doors",
    description:
      "Conquer rugged trails and steep hills with this durable and lightweight mountain bike. Built with advanced suspension and high-traction tires, it's perfect for off-road adventures and challenging terrains.",
  },
];
