export const Routes = {
  OtpScreen: "OtpScreen",
  Auth: {
    welcome: "WelcomeScreen",
    login: "login",
    signup: "SignUp",
    forgerPassword: "forgetPassword",
    socialAuthScreen: "SocicalAuthScreen",
    otpVerificationScreen: "otpVerificationScreen",
    newPasswordScreen: "newPasswordScreen",
    subAdmin: "subAdmin",
  },
  Main: {
    container: "Container",
  },
  Home: {
    HomeScreen: "HomeScreen",
    OrderScreen: "OrderScreen",
    NotificationScreen: "NotificationScreen",
    ProfileScreen: "ProfileScreen",
    productDetail: "ProductDetail",
    cartScreen: "cartScreen",
    DeliveryAddress: "DeliveryAddress",
    UpdateDelivery: "UpdateDelivery",
    EditProfile: "EditProfile",
    Language: "Language",
  },
  Admin: {
    ManageCategories: "ManageCategories",
    ManagePrducts: "ManageProducts",
    AddProducts: "AddProducts",
    AddAdmins: "AddAdmins",
    AddCategory: "AddCategory",
    GoldNSilverScreen: "GoldNSilverScreen",
    UserOrderDetail: "UserOrderDetail",
  },
  Chat: {
    ChatListing: "ChatListingScreen",
    ChatScreen: "ChatScreen",
  },
};
